spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contacts
    username: root
    password: d@noDAM96
    driver-class-name: com.mysql.jdbc.Driver

  logging:
    level:
      root: INFO
      com.example: DEBUG

